@echo off
setlocal
cd /d "%~dp0"
REM ============================================================
REM GreenRhino Huawei (AppGallery) PWA listing prep
REM No native compile: Huawei runs the PWA in AppGallery WebView.
REM You still need to deploy the PWA and submit via AppGallery console.
REM ============================================================
echo ============================================================
echo GreenRhino Huawei (AppGallery) PWA listing prep
echo ============================================================
echo [1/4] Deploy your PWA to a public HTTPS URL first.
echo       Use CloudStudio / OBS+CDN / GitHub Pages / any static host.
echo       Files: index.html sw.js src public icons manifest.webmanifest favicon.svg
set /p "PWA_URL=Enter your deployed PWA URL (https://...): "
echo [2/4] Place digital-asset file at: %PWA_URL%/.well-known/assetlinks.json
echo       Copy: clients\huawei\assetlinks.json  (generated by build-assets.mjs)
echo       Then replace REPLACE_WITH_YOUR_APP_SIGNING_SHA256_FINGERPRINT
echo       with your AppGallery app signing SHA256 (AppGallery console ^> App signature).
echo [3/4] Prepare listing assets:
echo       icon:          clients\assets\icon-512.png
echo       screenshots:   pick 3-5 from audit-*.png (phone portrait + tablet landscape)
echo       feature graphic: clients\huawei\listing\feature-graphic.svg (export 1024x500 PNG)
echo       description:    clients\huawei\listing\description-zh.txt
echo       privacy:        clients\huawei\listing\privacy.txt
echo [4/4] AppGallery console:
echo       New app ^> PWA/quick app ^> start URL = %PWA_URL%
echo       Upload icon/screenshots/feature graphic, submit for review.
echo       After approve, it is listed on Huawei devices.
pause
