@echo off
setlocal
cd /d "%~dp0"
REM ============================================================
REM GreenRhino Huawei AppGallery PWA listing prep (dual apps)
REM   Huawei devices lack GMS, can't run TWA; must publish PWA.
REM   Each app = independent PWA + independent assetlinks +
REM   independent listing folder.
REM
REM   Music  -> https://greenrhino-music.pages.dev  (green)
REM   Player -> https://greenrhino-player.pages.dev (amber)
REM
REM Prereq:
REM   1) Both CF Pages sites deployed (see deploy-pwa.mjs)
REM   2) assetlinks.json copied to each site /.well-known/
REM      (auto-generated by build-web.mjs in release/pwa-site-*/)
REM   3) If signing fingerprint changes, re-run:
REM      node clients/build-assets.mjs
REM ============================================================

echo ============================================================
echo   GreenRhino Huawei AppGallery PWA listing prep (dual apps)
echo ============================================================
echo.

REM ---------- Step 1: pre-check ----------
echo [1/3] Checking prerequisites ...
set "MUSIC_DIR=huawei-music"
set "PLAYER_DIR=huawei-player"

if not exist "%MUSIC_DIR%\listing\icon-512.png" (
  echo   [MISSING] %MUSIC_DIR%\listing\icon-512.png - run node build-assets.mjs
) else (
  echo   [OK] %MUSIC_DIR%\listing\icon-512.png
)
if not exist "%PLAYER_DIR%\listing\icon-512.png" (
  echo   [MISSING] %PLAYER_DIR%\listing\icon-512.png - run node build-assets.mjs
) else (
  echo   [OK] %PLAYER_DIR%\listing\icon-512.png
)
if not exist "%MUSIC_DIR%\assetlinks.json" (
  echo   [MISSING] %MUSIC_DIR%\assetlinks.json
) else (
  echo   [OK] %MUSIC_DIR%\assetlinks.json
)
if not exist "%PLAYER_DIR%\assetlinks.json" (
  echo   [MISSING] %PLAYER_DIR%\assetlinks.json
) else (
  echo   [OK] %PLAYER_DIR%\assetlinks.json
)

REM ---------- Step 2: assetlinks deployment ----------
echo.
echo [2/3] PWA deployment notes
echo ------------------------------------------------------------
echo   Each site must serve assetlinks.json at /.well-known/:
echo.
echo     Music  : copy %MUSIC_DIR%\assetlinks.json to  https://greenrhino-music.pages.dev/.well-known/assetlinks.json
echo     Player : copy %PLAYER_DIR%\assetlinks.json to  https://greenrhino-player.pages.dev/.well-known/assetlinks.json
echo.
echo   Cloudflare Pages users: build-web.mjs already writes these to
echo     release\pwa-site-music\.well-known\assetlinks.json
echo     release\pwa-site-player\.well-known\assetlinks.json
echo   Just upload the release folder to CF Pages as usual.
echo   Fingerprint (0fec2838...c77e) is already correct.

REM ---------- Step 3: AppGallery submission checklist ----------
echo.
echo [3/3] AppGallery console submission
echo ============================================================
echo.
echo   [MUSIC APP]
echo     App type:    PWA / QuickApp
echo     Start URL:   https://greenrhino-music.pages.dev/
echo     Icon:          %MUSIC_DIR%\listing\icon-512.png
echo     Feature gfx:   %MUSIC_DIR%\listing\feature-graphic-1024x500.png
echo     Screenshots:   %MUSIC_DIR%\listing\screenshots\*.png
echo     Description:   %MUSIC_DIR%\listing\description-zh.txt
echo     Privacy URL:   %MUSIC_DIR%\listing\privacy.txt (host on your own page)
echo.
echo   [PLAYER APP]
echo     App type:    PWA / QuickApp
echo     Start URL:   https://greenrhino-player.pages.dev/
echo     Icon:          %PLAYER_DIR%\listing\icon-512.png
echo     Feature gfx:   %PLAYER_DIR%\listing\feature-graphic-1024x500.png
echo     Screenshots:   %PLAYER_DIR%\listing\screenshots\*.png
echo     Description:   %PLAYER_DIR%\listing\description-zh.txt
echo     Privacy URL:   %PLAYER_DIR%\listing\privacy.txt (host on your own page)
echo.
echo   NOTE: Huawei requires portrait screenshots ratio 0.75-1.77
echo         (phone) and landscape 1.33-1.77 (tablet).
echo         Old mixed screenshots in clients\huawei\listing\screenshots\
echo         are for the merged v14 app - do NOT use them for dual apps.
echo ============================================================

pause